version: '3.8'

services:
  db:
    image: postgres:15
    container_name: learning_app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: learning_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: